# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [58]:
import numpy as np
arr=np.random.randint(0, 20, (28,))
arr=[round((i - np.min(arr))/(np.max(arr) - np.min(arr)), 3) for i in arr]
a=np.array(arr)
a.reshape(4, 7)

array([[ 0.526,  0.895,  0.842,  0.526,  0.263,  0.842,  0.158],
       [ 0.737,  0.316,  0.105,  0.105,  0.474,  0.105,  0.526],
       [ 0.684,  0.947,  0.421,  0.526,  0.000,  0.895,  1.000],
       [ 0.105,  0.263,  0.158,  0.579,  0.474,  0.474,  0.368]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [59]:
arr=np.random.randint(0, 10, (8, 10))
print(arr[0], sum(arr[0, :]))
print(arr[1], sum(arr[1, :]))
print(arr[2], sum(arr[2, :]))
print(arr[3], sum(arr[3, :]))
print(arr[4], sum(arr[4, :]))
print(arr[5], sum(arr[5, :]))
print(arr[6], sum(arr[6, :]))
print(arr[7], sum(arr[7, :]))
min(sum(arr[i, :]) for i in range(len(arr)))

[9 0 7 0 6 9 4 5 2 3] 45
[1 3 9 3 9 9 4 3 5 0] 46
[5 6 3 1 0 5 7 8 0 1] 36
[1 6 7 2 6 6 7 2 0 8] 45
[9 3 5 6 0 3 0 9 8 9] 52
[8 3 1 6 8 4 7 1 9 4] 51
[0 5 7 5 1 0 8 3 8 9] 46
[7 8 1 4 9 7 8 3 4 4] 55


36

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [60]:
v1=np.random.randint(0, 100, (3,))
v2=np.random.randint(0, 100, (3,))
print(v1, v2, sep='\n')
np.linalg.norm(v1-v2)

[37 16  7]
[84 77 58]


92.36341266973628

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [61]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
np.set_printoptions(formatter={'float':'{: 0.3f}'.format})
print(np.linalg.inv(A) @ (C * -1) @ np.linalg.inv(B))

[[ 1.000  0.000]
 [-2.000  1.000]
 [ 3.000 -4.000]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [62]:
import numpy as np
arr=np.loadtxt('minutes_n_ingredients.csv', dtype = int, delimiter = ',')
arr[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [63]:
print('Cреднее значение второго столбца: ', np.mean(arr[:, 1]))
print('Mинимум второго столбца: ', min(arr[:, 1]))
print('Mаксимум второго столбца: ', max(arr[:, 1]))
print('Mедиана второго столбца: ', np.median(arr[:, 1]))
print('Cреднее значение третьего столбца: ', np.mean(arr[:, 2]))
print('Mинимум третьего столбца: ', min(arr[:, 2]))
print('Mаксимум третьего столбца: ', max(arr[:, 2]))
print('Mедиана третьего столбца: ', np.median(arr[:, 2]))

Cреднее значение второго столбца:  21601.00169
Mинимум второго столбца:  0
Mаксимум второго столбца:  2147483647
Mедиана второго столбца:  40.0
Cреднее значение третьего столбца:  9.05528
Mинимум третьего столбца:  1
Mаксимум третьего столбца:  39
Mедиана третьего столбца:  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [64]:
np.quantile(arr[:, 1], 0.75)

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [65]:
print(np.sum(arr[:, 1]==0))
arr[:, 1][arr[:, 1] == 0] = 1
arr

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [66]:
len(np.unique(arr))

100544

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [67]:
print(np.unique(arr[:, 2]), len(np.unique(arr[:, 2])), sep='\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [68]:
arr1=[arr[i] for i in range(len(arr)) if arr[i][2]<6]
arr1

[array([446597,     15,      5]),
 array([204134,      5,      3]),
 array([25623,     6,     4]),
 array([484223,     18,      4]),
 array([63150,   250,     4]),
 array([70453,    25,     4]),
 array([66842,     2,     4]),
 array([337928,     55,      4]),
 array([140245,      5,      5]),
 array([75313,   603,     5]),
 array([98524,    40,     3]),
 array([377936,     65,      5]),
 array([87295,    20,     3]),
 array([94928,     5,     5]),
 array([210528,     70,      3]),
 array([317583,     65,      4]),
 array([360691,     13,      4]),
 array([229471,     30,      5]),
 array([297759,     65,      5]),
 array([42314,    60,     5]),
 array([341622,     10,      5]),
 array([43341,    40,     5]),
 array([111500,     15,      4]),
 array([271217,     10,      4]),
 array([316184,     15,      5]),
 array([408293,     35,      4]),
 array([56776,    70,     3]),
 array([180800,      5,      3]),
 array([523799,      5,      4]),
 array([145249,     80,      5]),
 array([50737

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [69]:
arr1=[round(arr[i, 2]/arr[i, 1], 3) for i in range(len(arr)) if arr[i, 1]!=0]
np.set_printoptions(formatter={'float':'{: 0.3f}'.format})
print(max(arr1), arr1, sep='\n')

24.0
[0.267, 0.28, 0.6, 1.2, 0.233, 0.175, 0.5, 0.333, 1.286, 0.35, 0.308, 0.583, 0.129, 0.6, 0.2, 0.667, 0.583, 0.039, 0.162, 0.3, 0.8, 0.157, 0.019, 0.073, 0.117, 0.212, 0.15, 0.222, 0.1, 0.016, 0.55, 0.054, 0.1, 0.092, 0.233, 0.073, 0.02, 0.25, 0.156, 0.4, 0.8, 0.16, 0.32, 0.145, 2.0, 0.073, 0.4, 1.0, 0.24, 0.4, 0.457, 0.562, 0.533, 0.3, 0.2, 0.008, 0.02, 0.075, 0.4, 0.077, 0.15, 1.0, 0.043, 0.014, 0.7, 0.157, 0.2, 0.069, 0.462, 0.1, 0.4, 0.4, 0.3, 0.12, 0.162, 0.28, 0.062, 0.067, 0.308, 0.167, 0.077, 0.333, 0.046, 0.003, 0.067, 0.52, 0.114, 0.12, 0.2, 0.6, 0.085, 0.083, 0.143, 0.273, 0.045, 0.3, 0.007, 0.533, 0.5, 1.375, 0.2, 0.064, 0.727, 0.4, 0.325, 0.125, 0.117, 0.7, 0.107, 0.533, 0.267, 0.222, 0.107, 1.4, 0.9, 0.321, 0.2, 0.233, 0.486, 0.4, 0.212, 0.086, 0.333, 0.114, 0.267, 0.043, 0.6, 0.005, 0.286, 0.4, 0.24, 0.3, 0.5, 0.171, 0.6, 0.275, 0.36, 0.117, 0.267, 0.244, 0.8, 0.156, 0.138, 0.1, 0.061, 0.733, 0.25, 0.267, 0.6, 0.233, 0.062, 0.111, 0.533, 0.343, 0.4, 0.212, 0.138, 0.3

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [70]:
arr[arr[:, 1].argsort()][::-1][:100][:, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [71]:
from numpy import random as rd
recipes_list = [arr[rd.randint(len(arr))] for i in range(10)]
recipes_list

[array([102287,     10,     11]),
 array([315848,      2,      2]),
 array([94292,    60,     6]),
 array([223303,      2,      4]),
 array([143244,     30,      8]),
 array([80900,    70,     4]),
 array([33781,     5,     5]),
 array([322722,     30,      7]),
 array([115976,     35,     10]),
 array([118477,     75,     17])]

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [72]:
sr_r=np.mean(arr[:, 2])
len([arr[i] for i in range(len(arr)) if arr[i, 2]<sr_r])*100/len(arr)

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [73]:
arr1=np.append(arr, np.array([arr[:, 1]<=20] and [arr[:, 2]<=5]).reshape(-1,1).astype('int'), axis=1)
arr1

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [38]:
(' '.join(pr_list)).count('1')/len(arr)

0.09552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.